[package]
name = "simple-wal"
version = "0.1.0"
authors = ["James Laver <james.laver@gmail.com>"]
edition = "2018"

[target.'cfg(target_family="unix")'.dependencies]
libc = "0.2.79"

[dev-dependencies]
